### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity 

### ISSUE THREAD

**Issue by wawa3tyt** [marcohc/roboto-calendar-view#29]
Android Studio 3.6.1

I tried use the below implementation in the sample project instead of the library
implementation 'com.github.marcohc:robotocalendarview:3.6.1'

and i get the below error when launching the sample app

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.marcohc.robotocalendarsample, PID: 19606
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.marcohc.robotocalendarsample/com.marcohc.robotocalendar.sample.MainActivity}: android.view.InflateException: Binary XML file line #5 in com.marcohc.robotocalendarsample:layout/activity_main: Binary XML file line #5 in com.marcohc.robotocalendarsample:layout/activity_main: Error inflating class com.marcohc.robotocalendar.RobotoCalendarView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: android.view.InflateException: Binary XML file line #5 in com.marcohc.robotocalendarsample:layout/activity_main: Binary XML file line #5 in com.marcohc.robotocalendarsample:layout/activity_main: Error inflating class com.marcohc.robotocalendar.RobotoCalendarView
     Caused by: android.view.InflateException: Binary XML file line #5 in com.marcohc.robotocalendarsample:layout/activity_main: Error inflating class com.marcohc.robotocalendar.RobotoCalendarView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createView(LayoutInflater.java:774)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:237)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1067)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.marcohc.robotocalendar.sample.MainActivity.onCreate(MainActivity.java:48)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/github/inflationx/viewpump/ViewPump;
        at com.marcohc.robotocalendar.RobotoCalendarView.init(RobotoCalendarView.java:212)
        at com.marcohc.robotocalendar.RobotoCalendarView.<init>(RobotoCalendarView.java:130)
        	... 35 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.inflationx.viewpump.ViewPump" on path: DexPathList[[zip file "/data/app/~~pqXAq33kYFw3NqBT98BOAw==/com.marcohc.robotocalendarsample-72Al5ImUnSHGRpLy5plsUg==/base.apk"],nativeLibraryDirectories=[/data/app/~~pqXAq33kYFw3NqBT98BOAw==/com.marcohc.robotocalendarsample-72Al5ImUnSHGRpLy5plsUg==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 37 more

**Comment by dgudim** [comment]
+ getting the same error
